web/router.ex
defmodule Erande.Router do
  use Erande.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Erande do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/ranking/", RankingController, :ranking
    get "/questions/answerclean", QuestionController, :answerclean
    resources "/questions", QuestionController do
      resources "/solutions", SolutionController
      get "/solutions/:id/mark", SolutionController, :mark
      get "/solutions/:id/unmark", SolutionController, :unmark
    end
    get "/questions/:id/propose", QuestionController, :propose_question
    get "/questions/:id/unpropose", QuestionController, :unpropose
    get "/questions/:id/answercheck", QuestionController, :answercheck
    get "/questions/:id/answeropen", QuestionController, :answeropen
  end

  scope "/auth", Erande do
    pipe_through [:browser]

    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :callback
    post "/:provider/callback", AuthController, :callback
    delete "/logout", AuthController, :delete
  end

  # Other scopes may use custom stacks.
  # scope "/api", Erande do
  #   pipe_through :api
  # end
end

web/models/solution.ex
defmodule Erande.Solution do
  use Erande.Web, :model

  schema "solutions" do
    field :body, :string

    belongs_to :question, Erande.Question, foreign_key: :question_id
    has_one :collectanswer, Erande.Collectanswer
    has_many :answers, Erande.Answer
    timestamps
  end

  @required_fields ~w(body question_id)
  @optional_fields ~w()

  @doc """
  Creates a changeset based on the `model` and `params`.

  If no params are provided, an invalid changeset is returned
  with no validation performed.
  """
  def changeset(model, params \\ :empty) do
    model
    |> cast(params, @required_fields, @optional_fields)
  end
end

web/controllers/solution_controller.ex
## ---------------------------
## 解答選択肢に関連するRESTコントローラー
## ---------------------------
defmodule Erande.SolutionController do
  use Erande.Web, :controller

  alias Erande.Solution
  alias Erande.Question
  alias Erande.Answer
  alias Erande.Collectanswer

  plug :scrub_params, "solution" when action in [:create, :update]

  # get /questions/{question_id}/solutions/
  def index(conn, %{"question_id" => question_id}) do
    question = Repo.get(Question, question_id)
    solutions = Repo.all(from(s in Solution, where: s.question_id == ^question_id, order_by: s.id, preload: :collectanswer))
    render(conn, "index.html", question_id: question_id, solutions: solutions, question: question, current_user: get_session(conn, :current_user))
  end

  # get /questions/{question_id}/solutions/new
  def new(conn, %{"question_id" => question_id}) do
    changeset = Solution.changeset(%Solution{}, %{})
    render(conn, "new.html", question_id: question_id, changeset: changeset, current_user: get_session(conn, :current_user))
  end

  # post /questions/{question_id}/solutions/
  def create(conn, %{"solution" => solution_params}) do
    changeset = Solution.changeset(%Solution{}, solution_params)

    case Repo.insert(changeset) do
      {:ok, solution} ->
        conn
        |> put_flash(:info, "Solution created successfully.")
        |> redirect(to: question_solution_path(conn, :index, solution.question_id))
      {:error, changeset} ->
        render(conn, "new.html", question_id: solution_params["question_id"], changeset: changeset, current_user: get_session(conn, :current_user))
    end
  end

  # get /questions/{question_id}/solutions/{id}
  def show(conn, %{"id" => id}) do
    solution = Repo.get!(Solution, id)
    render(conn, "show.html", question_id: solution.question_id, solution: solution, current_user: get_session(conn, :current_user))
  end

  # get /questions/{question_id}/solutions/{id}/edit
  def edit(conn, %{"id" => id, "question_id" => question_id}) do
    solution = Repo.get!(Solution, id)
    changeset = Solution.changeset(solution, %{})
    render(conn, "edit.html", question_id: question_id, solution: solution, changeset: changeset, current_user: get_session(conn, :current_user))
  end

  # put /questions/{question_id}/solutions/{id}
  @spec update(Plug.Conn.t(), map) :: Plug.Conn.t()
  def update(conn, %{"id" => id, "solution" => solution_params}) do
    solution = Repo.get!(Solution, id)
    changeset = Solution.changeset(solution, solution_params)

    case Repo.update(changeset) do
      {:ok, solution} ->
        conn
        |> put_flash(:info, "Solution updated successfully.")
        |> redirect(to: question_solution_path(conn, :show, solution.question_id, solution))
      {:error, changeset} ->
        render(conn, "edit.html", question_id: solution.question_id, solution: solution, changeset: changeset, current_user: get_session(conn, :current_user))
    end
  end

  # delete /questions/{question_id}/solutions/{id}
  def delete(conn, %{"id" => id, "question_id" => question_id}) do
    solution = Repo.get!(Solution, id)

    # Here we use delete! (with a bang) because we expect
    # it to always work (and if it does not, it will raise).
    Repo.delete_all(from(c in Collectanswer, where: c.solution_id == ^id))
    Repo.delete_all(from(a in Answer, where: a.solution_id == ^id))
    Repo.delete!(solution)

    conn
    |> put_flash(:info, "Solution deleted successfully.")
    |> redirect(to: question_solution_path(conn, :index, question_id))
  end

  ## ---------------------------
  ## 選択した選択肢を正答としてマーク
  ## ---------------------------
  def mark(conn, %{"id" => id, "question_id" => question_id}) do
    solution = Repo.get!(Solution, id)
    collectanswer = Ecto.build_assoc(solution, :collectanswer, question_id: solution.question_id)
    Repo.insert!(collectanswer)
    conn
    |> put_flash(:info, "solution marked successfully.")
    |> redirect(to: question_solution_path(conn, :index, question_id))
  end

  ## ---------------------------
  ## 選択した選択肢の正答マークを削除
  ## ---------------------------
  def unmark(conn, %{"id" => id, "question_id" => question_id}) do
    Repo.delete_all(from(c in Collectanswer, where: c.solution_id == ^id))
    conn
    |> put_flash(:info, "solution unmarked successfully.")
    |> redirect(to: question_solution_path(conn, :index, question_id))
  end
end

web/views/solution_view.ex
defmodule Erande.SolutionView do
  use Erande.Web, :view
end

web/templates/solution/edit.html.eex
<h2>Edit solution</h2>

<%= render "form.html", question_id: @question_id, changeset: @changeset,
                        action: question_solution_path(@conn, :update, @question_id, @solution) %>

<%= link "Back", to: question_solution_path(@conn, :index, @question_id) %>

web/templates/solution/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= hidden_input f, :question_id, value: @question_id %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below:</p>
      <ul>
        <%= for {attr, message} <- f.errors do %>
          <li><%= humanize(attr) %> <%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :body, "Body", class: "control-label" %>
    <%= text_input f, :body, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

web/templates/solution/index.html.eex
<h2>問題</h2>
<ul>
  <li>
    <strong>タイトル:</strong>
    <%= @question.title %>
  </li>
  <li>
    <strong>問題文:</strong>
    <%= @question.body %>
  </li>
</ul>
<h2>解答一覧</h2>
<table class="table">
  <thead>
    <tr>
      <th>正答？</th>
      <th>文章</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for solution <- @solutions do %>
    <tr>
      <td>
        <%= if !is_nil(solution.collectanswer) do %>
          <font class="badge">正答</font>
        <%= end %>
      </td>
      <td>
        <%= solution.body %>
      </td>

      <td class="text-right">
        <%= if is_nil(solution.collectanswer) do %>
          <%= link "Mark", to: question_solution_path(@conn, :mark, @question_id, solution), class: "btn btn-default btn-xs" %>
        <%= else %>
          <%= link "UnMark", to: question_solution_path(@conn, :unmark, @question_id, solution), class: "btn btn-default btn-xs red" %>
        <%= end %>
        <%= link "Show", to: question_solution_path(@conn, :show, @question_id, solution), class: "btn btn-default btn-xs" %>
        <%= link "Edit", to: question_solution_path(@conn, :edit, @question_id, solution), class: "btn btn-default btn-xs" %>
        <%= link "Delete", to: question_solution_path(@conn, :delete, @question_id, solution), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger red btn-xs" %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<%= link "選択肢を追加", to: question_solution_path(@conn, :new, @question_id) %>
<br/>
<%= link "問題一覧に戻る", to: question_path(@conn, :index) %>

web/templates/solution/new.html.eex
<h2>New solution</h2>

<%= render "form.html", question_id: @question_id,  changeset: @changeset,
                        action: question_solution_path(@conn, :create, @question_id) %>

<%= link "Back", to: question_solution_path(@conn, :index, @question_id) %>

web/templates/solution/show.html.eex
<h2>Show solution</h2>

<ul>

  <li>
    <strong>Body:</strong>
    <%= @solution.body %>
  </li>

</ul>

<%= link "Edit", to: question_solution_path(@conn, :edit, @solution, @question_id) %>
<%= link "Back", to: question_solution_path(@conn, :index, @question_id) %>