web/router.ex
defmodule Erande.Router do
  use Erande.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Erande do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/ranking/", RankingController, :ranking
    get "/questions/answerclean", QuestionController, :answerclean
    resources "/questions", QuestionController do
      resources "/solutions", SolutionController
      get "/solutions/:id/mark", SolutionController, :mark
      get "/solutions/:id/unmark", SolutionController, :unmark
    end
    get "/questions/:id/propose", QuestionController, :propose_question
    get "/questions/:id/unpropose", QuestionController, :unpropose
    get "/questions/:id/answercheck", QuestionController, :answercheck
    get "/questions/:id/answeropen", QuestionController, :answeropen
  end

  scope "/auth", Erande do
    pipe_through [:browser]

    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :callback
    post "/:provider/callback", AuthController, :callback
    delete "/logout", AuthController, :delete
  end

  # Other scopes may use custom stacks.
  # scope "/api", Erande do
  #   pipe_through :api
  # end
end

web/models/question.ex
defmodule Erande.Question do
  use Erande.Web, :model

  schema "questions" do
    field :title, :string
    field :body, :string

    has_one  :proposed_question, Erande.ProposedQuestion
    has_many :solutions, Erande.Solution
    has_many :collectanswers, Erande.Collectanswer
    timestamps
  end

  @required_fields ~w(title body)
  @optional_fields ~w()

  @doc """
  Creates a changeset based on the `model` and `params`.

  If no params are provided, an invalid changeset is returned
  with no validation performed.
  """
  def changeset(model, params \\ :empty) do
    model
    |> cast(params, @required_fields, @optional_fields)
  end
end

web/controllers/question_controller.ex
## ----------------------
## 問題管理コントローラー
## ----------------------
defmodule Erande.QuestionController do
  use Erande.Web, :controller

  alias Erande.Question
  alias Erande.Solution
  alias Erande.Answer
  alias Erande.ProposedQuestion

  plug :scrub_params, "question" when action in [:create, :update]

  # get /questions/
  def index(conn, _params) do
    questions = Repo.all(from(q in Question, preload: :proposed_question))
    render(conn, "index.html", questions: questions, current_user: get_session(conn, :current_user))
  end

  # get /questions/new
  def new(conn, _params) do
    changeset = Question.changeset(%Question{}, %{})
    render(conn, "new.html", changeset: changeset, current_user: get_session(conn, :current_user))
  end

  # post /questions/
  def create(conn, %{"question" => question_params}) do
    changeset = Question.changeset(%Question{}, question_params)

    case Repo.insert(changeset) do
      {:ok, _question} ->
        conn
        |> put_flash(:info, "Question created successfully.")
        |> redirect(to: question_path(conn, :index))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset, current_user: get_session(conn, :current_user))
    end
  end

  # get /questions/:id
  def show(conn, %{"id" => id}) do
    question = Repo.get!(Question, id)
    solutions = Repo.all(from(s in Solution, where: s.question_id == ^question.id, order_by: s.id, preload: :collectanswer))
    query_answers = from a in Answer,
             left_join: s in Solution, on: s.id == a.solution_id and s.question_id == ^id,
             group_by: [a.solution_id],
             order_by: [asc: a.solution_id],
             select: {a.solution_id, count(a.solution_id)}
    answers = query_answers |> Repo.all |> Enum.map(fn {id, count} -> %{id => count} end)
    map_answers = merge_array_map(%{}, answers)
    IO.inspect question, pretty: true
    IO.inspect map_answers, pretty: true
    render(conn, "show.html", question: question, solutions: solutions, current_user: get_session(conn, :current_user), answers: map_answers)
  end

  def merge_array_map(src, [head|tail]) do
    merge_array_map(Map.merge(src, head), tail)
  end
  def merge_array_map(src, []) do
    src
  end

  # get /questions/:id/edit
  def edit(conn, %{"id" => id}) do
    question = Repo.get!(Question, id)
    changeset = Question.changeset(question, %{})
    render(conn, "edit.html", question: question, changeset: changeset, current_user: get_session(conn, :current_user))
  end

  # put /questions/:id
  def update(conn, %{"id" => id, "question" => question_params}) do
    question = Repo.get!(Question, id)
    changeset = Question.changeset(question, question_params)

    case Repo.update(changeset) do
      {:ok, question} ->
        conn
        |> put_flash(:info, "Question updated successfully.")
        |> redirect(to: question_path(conn, :show, question))
      {:error, changeset} ->
        render(conn, "edit.html", question: question, changeset: changeset, current_user: get_session(conn, :current_user))
    end
  end

  # delete /questions/:id
  def delete(conn, %{"id" => id}) do
    question = Repo.get!(Question, id)

    case Repo.one(from(s in Solution, select: count(s.id), where: s.question_id == ^id)) do
      x when x > 0 ->
        conn
        |> put_flash(:info, "選択肢を先に削除してください")
        |> redirect(to: question_path(conn, :index))

      _ ->
        Repo.delete_all(from(p in ProposedQuestion, where: p.question_id == ^id))
        # Here we use delete! (with a bang) because we expect
        # it to always work (and if it does not, it will raise).
        Repo.delete!(question)

        conn
        |> put_flash(:info, "Question deleted successfully.")
        |> redirect(to: question_path(conn, :index))
    end

  end

  # 問題公開
  def propose_question(conn, %{"id" => id}) do
    question = Repo.get!(Question, id)
               |> Repo.preload(solutions: from(s in Solution, order_by: s.id))
    Repo.delete_all(ProposedQuestion)
    proposed_question = Ecto.build_assoc(question, :proposed_question, status: "waiting")
    Repo.insert!(proposed_question)
    solutions = Repo.preload question.solutions, :collectanswer
    rs_solutions = Enum.map(solutions, fn(solution) -> %{id: solution.id, body: solution.body, correct: !is_nil(solution.collectanswer)} end)
    IO.inspect rs_solutions, pretty: true

    Erande.Endpoint.broadcast! "rooms:lobby", "proposed", %{question_id: question.id, question_title: question.title, question_body: question.body, solutions: rs_solutions}
    conn
    |> put_flash(:info, "問題を公開しました")
    |> redirect(to: question_path(conn, :show, id))
  end

  # 問題取り消し
  def unpropose(conn, _params) do
    Repo.delete_all(ProposedQuestion)
    Erande.Endpoint.broadcast! "rooms:lobby", "proposed", %{question_id: 0, question_title: "", question_body: "出題待ち", solutions: []}
    conn
    |> put_flash(:info, "問題を取り消ししました")
    |> redirect(to: question_path(conn, :index))
  end

  # アンサーチェック！
  def answercheck(conn, %{"id" => id}) do
    proposed_questions = Repo.all ProposedQuestion
    if length(proposed_questions) == 1 do
      [proposed_question] = proposed_questions
      changeset = Ecto.Changeset.change proposed_question, status: "dead"
      Repo.update!(changeset)
      query  = from s in Solution,
                   left_join: a in Answer, on: a.solution_id == s.id,
                   where: s.question_id == ^proposed_question.question_id,
                   group_by: s.id,
                   order_by: s.id,
                   select: {s.id, count(a.id)}
      answers = Repo.all(query) |> Enum.map(fn {id, count} -> %{id: id, count: count} end)
      Erande.Endpoint.broadcast! "rooms:lobby", "answercheck", %{answers: answers}
      IO.inspect answers, pretty: true
    end
    conn
    |> put_flash(:info, "問題画面に解答状況を反映しました")
    |> redirect(to: question_path(conn, :show, id))
  end

  # アンサーオープン
  def answeropen(conn, %{"id" => id}) do
    Erande.Endpoint.broadcast! "rooms:lobby", "answeropen", %{}
    conn
    |> put_flash(:info, "問題画面に解答を反映しました")
    |> redirect(to: question_path(conn, :show, id))
  end

  # 回答データをリセット
  def answerclean(conn, _param) do
    Repo.delete_all(Answer)
    conn
    |> put_flash(:info, "回答データを消去しました")
    |> redirect(to: question_path(conn, :index))
  end
end

web/views/question_view.ex
defmodule Erande.QuestionView do
  use Erande.Web, :view
end

web/templates/question/edit.html.eex
<h2>Edit question</h2>

<%= render "form.html", changeset: @changeset,
                        action: question_path(@conn, :update, @question) %>

<%= link "Back", to: question_path(@conn, :index) %>

web/templates/question/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below:</p>
      <ul>
        <%= for {attr, message} <- f.errors do %>
          <li><%= humanize(attr) %> <%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :title, "Title", class: "control-label" %>
    <%= text_input f, :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= label f, :body, "Body", class: "control-label" %>
    <%= text_input f, :body, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

web/templates/question/index.html.eex
<h2>問題一覧</h2>

<table class="table">
  <thead>
    <tr>
      <th>出題中</th>
      <th>タイトル</th>
      <th>問題文</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for question <- @questions do %>
    <tr>
      <td>
        <%= if !is_nil(question.proposed_question) do %>
          <font class="badge">出題中</font>
        <%= end %>
      </td>
      <td><%= question.title %></td>
      <td><%= question.body %></td>

      <td class="text-right">
        <%= link "出題", to: question_path(@conn, :propose_question, question), class: "btn btn-default btn-xs" %>
        <%= link "一覧", to: question_solution_path(@conn, :index, question), class: "btn btn-default btn-xs" %>
        <%= link "詳細", to: question_path(@conn, :show, question), class: "btn btn-default btn-xs" %>
        <%= link "編集", to: question_path(@conn, :edit, question), class: "btn btn-default btn-xs" %>
        <%= link "削除", to: question_path(@conn, :delete, question), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<%= link "New question", to: question_path(@conn, :new) %>
<%= link "回答データのリセット", to: question_path(@conn, :answerclean) %>
<%= link "ランキング", to: ranking_path(@conn, :ranking) %>

web/templates/question/new.html.eex
<h2>New question</h2>

<%= render "form.html", changeset: @changeset,
                        action: question_path(@conn, :create) %>

<%= link "Back", to: question_path(@conn, :index) %>

web/templates/question/show.html.eex
<h2>Show question</h2>

<ul>

  <li>
    <strong>Title:</strong>
    <%= @question.title %>
  </li>

  <li>
    <strong>Body:</strong>
    <%= @question.body %>
  </li>

</ul>

<h2>解答一覧</h2>
<table class="table">
  <thead>
  <tr>
    <th>正答？</th>
    <th>文章</th>
    <th>現在の回答数</th>

  </tr>
  </thead>
  <tbody>
  <%= for solution <- @solutions do %>
  <tr>
    <td>
      <%= if !is_nil(solution.collectanswer) do %>
      <font class="badge">正答</font>
      <%= end %>
    </td>
    <td>
      <%= solution.body %>
    </td>
    <td>
      <%= @answers[solution.id] %>
    </td>

  </tr>
  <% end %>
  </tbody>
</table>

<h3>コントロールパネル</h3>

<ul>
  <li><%= link "出題", to: question_path(@conn, :propose_question, @question), class: "btn btn-default btn-xs" %></li>
  <br>
  <li><%= link "取り消し", to: question_path(@conn, :unpropose, @question), class: "btn btn-default btn-xs" %></li>
  <br>
  <li><%= link "アンサーチェック！", to: question_path(@conn, :answercheck, @question), class: "btn btn-default btn-xs" %></li>
  <br>
  <li><%= link "正解オープン", to: question_path(@conn, :answeropen, @question), class: "btn btn-default btn-xs" %></li>
</ul>


<%= link "Edit", to: question_path(@conn, :edit, @question) %>
<%= link "Back", to: question_path(@conn, :index) %>